# This Makefile is generated by omake: https://github.com/ouonline/omake.git

CXX := g++

ifeq ($(debug), y)
	CXXFLAGS += -g
else
	CXXFLAGS += -O2 -DNDEBUG
endif

AR := ar

TARGET := libcpputils_shared.so libcpputils_static.a

.PHONY: all clean distclean

all: $(TARGET)

.PHONY: omake_phony_0
omake_phony_0:
	$(MAKE) debug=$(debug) libmath_static.a -C ../math

omake_dep_0_INCLUDE := -I..

omake_dep_0.text_utils.cpp.o: text_utils.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC $(omake_dep_0_INCLUDE) -c $< -o $@

cpputils_shared_OBJS := omake_dep_0.text_utils.cpp.o

cpputils_shared_LIBS := ../math/libmath_static.a

libcpputils_shared.so: $(cpputils_shared_OBJS) | omake_phony_0
	$(CXX) $(CXXFLAGS) -fPIC -Wextra -Werror -Wall -shared -o $@ $^ $(cpputils_shared_LIBS)

cpputils_static_OBJS := omake_dep_0.text_utils.cpp.o

libcpputils_static.a: $(cpputils_static_OBJS) | omake_phony_0
	$(AR) rc $@ $^

clean:
	rm -f $(TARGET) $(cpputils_shared_OBJS) $(cpputils_static_OBJS)

distclean:
	$(MAKE) clean
	$(MAKE) distclean -C ../math
