# This Makefile is generated by omake: https://github.com/ouonline/omake.git

CXX := g++

ifeq ($(debug), y)
	CXXFLAGS += -g
else
	CXXFLAGS += -O2 -DNDEBUG
endif

AR := ar

TARGET := libtext_utils_shared.so libtext_utils_static.a

.PHONY: all clean distclean

all: $(TARGET)

omake_dep_0.text_utils.cpp.o: text_utils.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

text_utils_shared_OBJS := omake_dep_0.text_utils.cpp.o

libtext_utils_shared.so: $(text_utils_shared_OBJS)
	$(CXX) $(CXXFLAGS) -fPIC -Wextra -Werror -Wall -shared -o $@ $^

text_utils_static_OBJS := omake_dep_0.text_utils.cpp.o

libtext_utils_static.a: $(text_utils_static_OBJS)
	$(AR) rc $@ $^

clean:
	rm -f $(TARGET) $(text_utils_shared_OBJS) $(text_utils_static_OBJS)

distclean:
	$(MAKE) clean
